FROM nexus.hcqis.org:18443/jenkinsdockeragents/ventechdockeragent:3

RUN apt-get install -y wget unzip
RUN cd /usr/local/bin && wget  https://releases.hashicorp.com/terraform/0.11.1/terraform_0.11.1_linux_amd64.zip?_ga=2.255088136.1676303900.1512399065-375781825.1512399065
RUN cd /usr/local/bin && mv terraform_0.11.1_linux_amd64.zip?_ga=2.255088136.1676303900.1512399065-375781825.1512399065 terraform.zip && unzip terraform.zip

RUN mkdir HQR-Terraform

COPY Terraform/HQR-Terraform/sandbox/ HQR-Terraform/
RUN cd /usr/local/bin && terraform init